### ISSUE TITLE
the axis of BatchNormalization problem

### ISSUE THREAD

**Issue by yuhsh24** [TeamSAIDA/DefogGAN#1]
Conv2D(depth * 2, (3, 3), strides=(1, 1), activation='relu', input_shape=input_shape, padding='same', data_format='channels_first')(img_input)
BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,.....)
I think the axis of BatchNormalization operation after conv2d shoud be 1，not be -1.

**Comment by Devkruth** [comment]
axis should be 1 if the previous layer data_format was Channels_first
